server:
  port: 8501


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spzx?characterEncoding=utf-8&userSSl=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml
logging:
  config: classpath:logback-spring.xml

spzx:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
  minio:
      endpointUrl:http://127.0.0.1:9000
      accessKey:minioadmin
      secretKey:minioadmin
      bucketName:spzx-bucket

